version: "3.8"

services:
  truescopemarketing:
    build:
      context: .
      dockerfile: Dockerfile
    image: truescopemarketing:latest
    container_name: truescopemarketing
    ports:
      - "3007:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
